KERJA/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('landingpage/', include('landingpage.urls')),
]

landingpage/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import *

app_name = "landingpage"
urlpatterns = [
    path('', home, name="home"),
]

landingpage/models.py
from django.db import models

# Create your models here.

landingpage/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'landingpage/navbar.html')

landingpage/templates/landingpage/navbar.html
{%extends 'base.html'%}
{%block content%}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="profil my-2">
                <h2 class="text-center">Profil</h2>
                <p>Berdiri sejak tahun 2017, 3D Track GPS Tracker berfokus pada peningkatan efisiensi dan keamanan armada dengan teknologi GPS Tracking. Perkembangan zaman yang pesat serta kemajuan teknologi yang makin meningkat, maka kriminalisasi pun ikut meningkat. Kami 3D Track GPS Tracker, hadir untuk membantu serta menjalin relasi dari berbagai kalangan, dengan memberikan keamanan dan kenyamanan berinvestasi dalam bentuk perangkat keamanan armada. 
                        3D Track telah banyak membantu perusahaan besar ataupun kecil bahkan perorangan di Indonesia dalam peningkatan produktifitas serta efisiensi melalui pemantauan posisi seluruh armada secara real-time dengan menggunakan GPS yang bekerja selama 24 jam x 7 hari non-stop. 
                        3D Track dikembangkan dengan tujuan menjunjung tinggi tanggung jawab kerja di samping memberikan layanan yang terbaik dan harga yang kompetitif. Kepuasan Customer adalah hal utama yang selalu kami jaga.
                        </p>
            </div>
            
            
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="visi-misi my-2">
                <h2 class="text-center">Visi dan Misi</h2>
                <h3>Misi</h3>
                <p>Menyediakan fasilitas tracking untuk customer perusahaan dan individu, memberikan layanan terbaik berkualitas dengan support yang cepat, dan menjalin kemitraan dengan calon customer maupun customer kami.</p>
                <h3>Visi</h3>
                <p>Sebagai penyedia fasilitas dan layanan Tracking paling terdepan di era globalisasi yang kompetitif, terpercaya dan handal di Indonesia.</p>   
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <div class="capt my-2">
                <h6>Konsep 3D Track untuk penjualan tidak hanya jual beli putus, tetapi untuk bermitra. Baik untuk calon cust kami maupun sudah menjadi customer kami. Karena bermitra dapat melihat jangka panjangnya. Ketika ada masalah cust tidak akan bimbang atau malu bertanya kepada kami. Begitu pula kami ketika untuk menawarkan produk produk kami, kami akan menawarkan produk2 terbaik. Tanpa ada rasa sungkan. Tidak hanya bernilai materi antara kami dengan pihak cust. Tetapi kami dan mereka adalah mitra. 
    
                    Sistem manajemen CV. 3D Track membantu Perusahaan dan Organisasi untuk mewujudkan peningkatan efisiensi yang signifikan dan mendapatkan wawasan berharga tentang semua aspek dari operasi armada mereka dengan melacak, memantau dan mengelola aset bergerak mereka secara real time pada waktu tertentu.
                </h6>
            </div>
        </div>
    </div>
</div>

{%endblock%}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="{% static "css/temp.css" %}" type="text/css" rel="stylesheet"/>
    <link href="https://fonts.googleapis.com/css?family=Mada:700|Nunito:700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-social/5.1.1/bootstrap-social.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    {% block head %}
        <!-- head -->
    {% endblock %}
    <title>
        {% block title %}
        <!-- title -->
        {% endblock %}
    </title>
    
    <!-- bootstrap csss -->
</head>

<body>
    <nav>
        {% include "navbar.html" %}
    </nav>
    <content>
            {% block content %}
                <!-- content goes here -->
               
            {% endblock %}
    </content>
    {%include 'footer.html' %}
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block script %}
    {% endblock %}
</body>
</html>

templates/footer.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'css/GeneralStyle.css' %}">
<div class="footer">
</div>

<div class="footer_info">
    <div class="container_info">
        <div class="info">
            <h1 class="judul_info">3D Track GPS Traker</h1>
            <p class="subjudul_info">Jl. H. Sa'anan 1 No. 37 Rt. 004/06 <br>
                Kel. Kembangan Utara, Kec. Kembangan<br>Jakarta Barat. <br>
                <a class="text-white" href = "tel:+6281133322737"> 0811-3332-2737</a><br>
                <a class="text-white"href = "tel:+6282210075329">0822-1007-5329</a> <br>
                </p>
        </div>

        <div class="info">
            <h1 class="judul_info">Tentang Kami</h1>
            <p class="subjudul_info">aaaaaaaa</p>
        </div>

        <div class="info">
            <h1 class="judul_info" style="text-align: center">Official Partner</h1>
            <a class="subjudul_info" href="#"><img src="{% static 'image/telkomsel.png' %}" style="width:100px;"></a>
            <a class="subjudul_info" href="#"><img src="{% static 'image/apple.png' %}" style="width:100px;"></a>
            <a class="subjudul_info" href="#"><img src="{% static 'image/google.png' %}" style="width:100px;"></a>
            
        </div>
    </div>
</div>

templates/navbar.html
{% load staticfiles %}

    <nav class="navbar navbar-expand-lg navbar-dark">
        <a class="navbar-brand active" href="{% url 'landingpage:home' %}"><img src="{% static 'image/logo.jpg' %}" style="width:100px;"><span class="sr-only">(current)</span></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                     <a class="nav-link" href="#landingpage">HOME</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">TENTANG KAMI</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">PRODUK</a>
                </li>
                 <li class="nav-item">
                    <a class="nav-link" href="#">PROMO</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">KONTAK</a>
                </li>
            </ul>
        </div>
    </nav>